version: "3.5"

services:

  mysql:
    build:
      context: ./docker/mysql
      args:
        - MYSQL_VERSION=latest
    environment:
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - TZ=UTC
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "${DOCKER_PMA_PORT}:80"
    depends_on:
      - mysql

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - LISTEN_PORT=3000
    ports:
    - 3001:3000
    depends_on:
      - mysql

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  mysql_data:
